//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Article { get; set; }
        public string image { get; set; }
        public string TovarName { get; set; }
        public string Warranty { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> IDCategories { get; set; }
        public Nullable<int> IDProvider { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
